language: node_js
node_js:
  - "13"
cache:
  directories:
    - "node_modules"
    - "client/node_modules"
install:
  - npm install
  - npm install --prefix client
script:
  - npm run test
  - npm run build:client
deploy:
  provider: pages
  local-dir: docs
  repo: mapitout/mapitout.github.io
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
  target-branch: master
  name: Mapitout Travis Worker
  email: team-travis@mapitout.com