export default {
  accounts: [
    {
      "account_id": "pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb",
      "balances": {
        "available": 100,
        "current": 110,
        "iso_currency_code": "USD",
        "limit": null,
        "unofficial_currency_code": null
      },
      "mask": "0000",
      "name": "Plaid Checking",
      "official_name": "Plaid Gold Standard 0% Interest Checking",
      "subtype": "checking",
      "type": "depository"
    },
    {
      "account_id": "oQv5baLV3KsJ79VW8XyKHKLGoaRzgdfRqva1v",
      "balances": {
        "available": 200,
        "current": 210,
        "iso_currency_code": "USD",
        "limit": null,
        "unofficial_currency_code": null
      },
      "mask": "1111",
      "name": "Plaid Saving",
      "official_name": "Plaid Silver Standard 0.1% Interest Saving",
      "subtype": "savings",
      "type": "depository"
    },
    {
      "account_id": "gdobpqJVyRI16ypJVxzKCwy8qDa5zoug8ybP9",
      "balances": {
        "available": null,
        "current": 1000,
        "iso_currency_code": "USD",
        "limit": null,
        "unofficial_currency_code": null
      },
      "mask": "2222",
      "name": "Plaid CD",
      "official_name": "Plaid Bronze Standard 0.2% Interest CD",
      "subtype": "cd",
      "type": "depository"
    },
    {
      "account_id": "8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge",
      "balances": {
        "available": null,
        "current": 410,
        "iso_currency_code": "USD",
        "limit": 2000,
        "unofficial_currency_code": null
      },
      "mask": "3333",
      "name": "Plaid Credit Card",
      "official_name": "Plaid Diamond 12.5% APR Interest Credit Card",
      "subtype": "credit card",
      "type": "credit"
    },
    {
      "account_id": "EbJ97Xr4yqIZM7zraRE8cXZvb63oEBCXx6wrd",
      "balances": {
        "available": 43200,
        "current": 43200,
        "iso_currency_code": "USD",
        "limit": null,
        "unofficial_currency_code": null
      },
      "mask": "4444",
      "name": "Plaid Money Market",
      "official_name": "Plaid Platinum Standard 1.85% Interest Money Market",
      "subtype": "money market",
      "type": "depository"
    },
    {
      "account_id": "WV3RJn4GQ1Hem8rwX9nWfRWz46x8lAflZBrXA",
      "balances": {
        "available": null,
        "current": 320.76,
        "iso_currency_code": "USD",
        "limit": null,
        "unofficial_currency_code": null
      },
      "mask": "5555",
      "name": "Plaid IRA",
      "official_name": null,
      "subtype": "ira",
      "type": "investment"
    },
    {
      "account_id": "A6Jn1X93GDsgM5qjlRvecMAbRqoDVwi1rB7ab",
      "balances": {
        "available": null,
        "current": 23631.9805,
        "iso_currency_code": "USD",
        "limit": null,
        "unofficial_currency_code": null
      },
      "mask": "6666",
      "name": "Plaid 401k",
      "official_name": null,
      "subtype": "401k",
      "type": "investment"
    },
    {
      "account_id": "GAJQwXkPlrikpzo3dBGEF9KWzxE4vaH1MZlqz",
      "balances": {
        "available": null,
        "current": 65262,
        "iso_currency_code": "USD",
        "limit": null,
        "unofficial_currency_code": null
      },
      "mask": "7777",
      "name": "Plaid Student Loan",
      "official_name": null,
      "subtype": "student",
      "type": "loan"
    }
  ],
  item: {
    available_products: ['assets',
      'balance',
      'credit_details',
      'identity',
      'income',
      'liabilities'
    ],
    billed_products: ['auth', 'transactions'],
    consent_expiration_time: null,
    error: null,
    institution_id: 'ins_5',
    item_id: 'r1vJqP5VaBtq6DlwVLbecryAZjgwKgFlxvMgM',
    webhook: ''
  },
  request_id: 'eITXgg7E7JwIEFl',
  total_transactions: 51,
  transactions: [{
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 2078.5,
      authorized_date: null,
      category: [Array],
      category_id: '16000000',
      date: '2020-02-24',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'AUTOMATIC PAYMENT - THANK',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'EbJ97Xr4yqIZM7zraRE8cXZArR6qABCXxyEbV',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '13005032',
      date: '2020-02-24',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'KFC',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: '8Agp6XRG1niQ5LmzN3BAcajVALQvVJhw3nrqr',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '19046000',
      date: '2020-02-24',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Madison Bicycle Shop',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'gdobpqJVyRI16ypJVxzKCwy7PxDm7oHg8oMW4',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'oQv5baLV3KsJ79VW8XyKHKLGoaRzgdfRqva1v',
      account_owner: null,
      amount: 25,
      authorized_date: null,
      category: [Array],
      category_id: '16001000',
      date: '2020-02-15',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'CREDIT CARD 3333 PAYMENT *//',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'L6JVMXbZBdsR6XPoGQaEUXbj1QVdj8CPj79wP',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 5.4,
      authorized_date: null,
      category: [Array],
      category_id: '22016000',
      date: '2020-02-15',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Uber',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: '7mopPkVAMGFNnoGr4jzmSMzKWlExKrCgJZ1eP',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'EbJ97Xr4yqIZM7zraRE8cXZvb63oEBCXx6wrd',
      account_owner: null,
      amount: 5850,
      authorized_date: null,
      category: [Array],
      category_id: '21006000',
      date: '2020-02-14',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'ACH Electronic CreditGUSTO PAY 123456',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'yywVd1blQPHZA7xowkLmcNkadw8Kazfy6GDxJ',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'gdobpqJVyRI16ypJVxzKCwy8qDa5zoug8ybP9',
      account_owner: null,
      amount: 1000,
      authorized_date: null,
      category: [Array],
      category_id: '21007000',
      date: '2020-02-14',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'CD DEPOSIT .INITIAL.',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'oQv5baLV3KsJ79VW8XyKHKLx5eaNxduRqjKEp',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 78.5,
      authorized_date: null,
      category: [Array],
      category_id: '17018000',
      date: '2020-02-13',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Touchstone Climbing',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'WV3RJn4GQ1Hem8rwX9nWfRWj3961jAulZR4gX',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: -500,
      authorized_date: null,
      category: [Array],
      category_id: '22001000',
      date: '2020-02-13',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'United Airlines',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'e3Lv6nJVk9hbDl1mVg6kFPvMmgeXM3tL9gVpG',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 12,
      authorized_date: null,
      category: [Array],
      category_id: '13005032',
      date: '2020-02-12',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'McDonald\'s',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'Q6lJzyWo4jsG6rNpXMb8c1BmVMLjmocpm1avn',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 4.33,
      authorized_date: null,
      category: [Array],
      category_id: '13005043',
      date: '2020-02-12',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Starbucks',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'Z6aqbRjV1osJZp3qV7rwH3VGa7QgGLTgq3b4w',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 89.4,
      authorized_date: null,
      category: [Array],
      category_id: '13005000',
      date: '2020-02-11',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'SparkFun',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'M6J7lXZM3asjXzPRwldnuL9GzlBaGxc96K7qb',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'oQv5baLV3KsJ79VW8XyKHKLGoaRzgdfRqva1v',
      account_owner: null,
      amount: -4.22,
      authorized_date: null,
      category: [Array],
      category_id: '21005000',
      date: '2020-02-10',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'INTRST PYMNT',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'pZv5g4XVxrs9mgQa8p1rujba6M15aZiLowKap',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '22001000',
      date: '2020-01-31',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'United Airlines',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'A6Jn1X93GDsgM5qjlRvecMAP7nqyPwC1r8ozB',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 6.33,
      authorized_date: null,
      category: [Array],
      category_id: '22016000',
      date: '2020-01-29',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Uber',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: '15QlJ8wpkohPN6BAzZ3wh85ZxJqrZjF5jzmBQ',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '13005000',
      date: '2020-01-26',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Tectra Inc',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'GAJQwXkPlrikpzo3dBGEF9K6PBxr6aC1Mankw',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 2078.5,
      authorized_date: null,
      category: [Array],
      category_id: '16000000',
      date: '2020-01-25',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'AUTOMATIC PAYMENT - THANK',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'm7v5Jx9Vzlf5wZQgv9nlFpaRNZ4WRDtLyEA6w',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '13005032',
      date: '2020-01-25',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'KFC',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'brZxpnjVAbSMJZxDVv9giE16Kbyz6ZHVbl38v',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '19046000',
      date: '2020-01-25',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Madison Bicycle Shop',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'nev54dJVkqHB7X3wvmjqhVdvEq4pvjt6loGvg',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'oQv5baLV3KsJ79VW8XyKHKLGoaRzgdfRqva1v',
      account_owner: null,
      amount: 25,
      authorized_date: null,
      category: [Array],
      category_id: '16001000',
      date: '2020-01-16',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'CREDIT CARD 3333 PAYMENT *//',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'e3Lv6nJVk9hbDl1mVg6kFPvrZWKAxbCL5k1lN',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 5.4,
      authorized_date: null,
      category: [Array],
      category_id: '22016000',
      date: '2020-01-16',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Uber',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'P6JbrVEpaPsrmpN7yk1vU1bvgWNJ4ah7WvZ9P',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'EbJ97Xr4yqIZM7zraRE8cXZvb63oEBCXx6wrd',
      account_owner: null,
      amount: 5850,
      authorized_date: null,
      category: [Array],
      category_id: '21006000',
      date: '2020-01-15',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'ACH Electronic CreditGUSTO PAY 123456',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'V6BWpJgAeMsNkgKlqm48Sp9KeWznvBuWPdeE6',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'gdobpqJVyRI16ypJVxzKCwy8qDa5zoug8ybP9',
      account_owner: null,
      amount: 1000,
      authorized_date: null,
      category: [Array],
      category_id: '21007000',
      date: '2020-01-15',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'CD DEPOSIT .INITIAL.',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'V6BWpJgAeMsNkgKlqm48Sp9KeWznvBuWPdeX3',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 78.5,
      authorized_date: null,
      category: [Array],
      category_id: '17018000',
      date: '2020-01-14',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Touchstone Climbing',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'e3Lv6nJVk9hbDl1mVg6kFPvrZWKAxbCL5k1mz',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: -500,
      authorized_date: null,
      category: [Array],
      category_id: '22001000',
      date: '2020-01-14',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'United Airlines',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'N6JRqXn1x4sgJENqbjGZceokwLydbaUW5KmgJ',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 12,
      authorized_date: null,
      category: [Array],
      category_id: '13005032',
      date: '2020-01-13',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'McDonald\'s',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'aKQekD3VWnSagpy7VMPmc7ldmvN4QVH7Q3LzJ',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 4.33,
      authorized_date: null,
      category: [Array],
      category_id: '13005043',
      date: '2020-01-13',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Starbucks',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: '4D1r6mV8eEhJKdMlXzejHQkEG8MJ6qudAM7Zb',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 89.4,
      authorized_date: null,
      category: [Array],
      category_id: '13005000',
      date: '2020-01-12',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'SparkFun',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'dB1wgbJVnyTp9KDRVQNjFWrG16gZNXuZQaemy',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'oQv5baLV3KsJ79VW8XyKHKLGoaRzgdfRqva1v',
      account_owner: null,
      amount: -4.22,
      authorized_date: null,
      category: [Array],
      category_id: '21005000',
      date: '2020-01-11',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'INTRST PYMNT',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: '7mopPkVAMGFNnoGr4jzmSMzaye7NdAcgnpLK9',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '22001000',
      date: '2020-01-01',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'United Airlines',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: '7mopPkVAMGFNnoGr4jzmSMzaye7NdAcgnpLxe',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 6.33,
      authorized_date: null,
      category: [Array],
      category_id: '22016000',
      date: '2019-12-30',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Uber',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'xyvrxMXVeNHQ7G3EZKnwcLKnqEXP8AFnVBvqK',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '13005000',
      date: '2019-12-27',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Tectra Inc',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'jNvbpzgVqDT3n1VXvlrBu6nGDzwXvet1LAqaP',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 2078.5,
      authorized_date: null,
      category: [Array],
      category_id: '16000000',
      date: '2019-12-26',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'AUTOMATIC PAYMENT - THANK',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'P6JbrVEpaPsrmpN7yk1vU1bvgWNJ4ah7WvZAz',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '13005032',
      date: '2019-12-26',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'KFC',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'N6JRqXn1x4sgJENqbjGZceokwLydbaUW5KmKe',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '19046000',
      date: '2019-12-26',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Madison Bicycle Shop',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: '4D1r6mV8eEhJKdMlXzejHQkEG8MJ6qudAM7MG',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'oQv5baLV3KsJ79VW8XyKHKLGoaRzgdfRqva1v',
      account_owner: null,
      amount: 25,
      authorized_date: null,
      category: [Array],
      category_id: '16001000',
      date: '2019-12-17',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'CREDIT CARD 3333 PAYMENT *//',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'jNvbpzgVqDT3n1VXvlrBu6nGDzwXvet1LAq83',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 5.4,
      authorized_date: null,
      category: [Array],
      category_id: '22016000',
      date: '2019-12-17',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Uber',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: '3oMKP5vg78TZqDyQ3MzBcrAJgone97iqnR3BE',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'EbJ97Xr4yqIZM7zraRE8cXZvb63oEBCXx6wrd',
      account_owner: null,
      amount: 5850,
      authorized_date: null,
      category: [Array],
      category_id: '21006000',
      date: '2019-12-16',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'ACH Electronic CreditGUSTO PAY 123456',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'D6J8oXwamlsaMV8Q4wpJc4yLMX16RNFvaQxJm',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'gdobpqJVyRI16ypJVxzKCwy8qDa5zoug8ybP9',
      account_owner: null,
      amount: 1000,
      authorized_date: null,
      category: [Array],
      category_id: '21007000',
      date: '2019-12-16',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'CD DEPOSIT .INITIAL.',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'D6J8oXwamlsaMV8Q4wpJc4yLMX16RNFvaQxBA',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 78.5,
      authorized_date: null,
      category: [Array],
      category_id: '17018000',
      date: '2019-12-15',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Touchstone Climbing',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'aKQekD3VWnSagpy7VMPmc7ldmvN4QVH7Q3L3A',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: -500,
      authorized_date: null,
      category: [Array],
      category_id: '22001000',
      date: '2019-12-15',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'United Airlines',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'BAJRwX5xnViQbdl7DevBcyAbl4avkqCw8jnQj',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 12,
      authorized_date: null,
      category: [Array],
      category_id: '13005032',
      date: '2019-12-14',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'McDonald\'s',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'r1vJqP5VaBtq6DlwVLbecryQZlW13mil6Mgng',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 4.33,
      authorized_date: null,
      category: [Array],
      category_id: '13005043',
      date: '2019-12-14',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Starbucks',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'zVvmJL5qZjHo57RKQrjqcQz978ZrRBuoLmWzL',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 89.4,
      authorized_date: null,
      category: [Array],
      category_id: '13005000',
      date: '2019-12-13',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'SparkFun',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'K6JnRXVQzxsno6P4VZbEip46QGl7VKuVANbLa',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: 'oQv5baLV3KsJ79VW8XyKHKLGoaRzgdfRqva1v',
      account_owner: null,
      amount: -4.22,
      authorized_date: null,
      category: [Array],
      category_id: '21005000',
      date: '2019-12-12',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'INTRST PYMNT',
      payment_channel: 'other',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'P6JbrVEpaPsrmpN7yk1vU1bvgWNJ4ah7WvZrP',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '22001000',
      date: '2019-12-02',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'United Airlines',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'dB1wgbJVnyTp9KDRVQNjFWrG16gZNXuZQaea8',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: 'pZv5g4XVxrs9mgQa8p1rujboA1PJgZCLoX4bb',
      account_owner: null,
      amount: 6.33,
      authorized_date: null,
      category: [Array],
      category_id: '22016000',
      date: '2019-11-30',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Uber',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'qMvRlkjVdztq7AQ1vRDZcPXEnjvog4Cd7MkZZ',
      transaction_type: 'special',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '13005000',
      date: '2019-11-27',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Tectra Inc',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'xyvrxMXVeNHQ7G3EZKnwcLKnqEXP8AFnVBvBp',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '13005032',
      date: '2019-11-26',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'KFC',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'BAJRwX5xnViQbdl7DevBcyAbl4avkqCw8jnjV',
      transaction_type: 'place',
      unofficial_currency_code: null
    },
    {
      account_id: '8Agp6XRG1niQ5LmzN3BAcaj5xQ7zpJTw3NAge',
      account_owner: null,
      amount: 500,
      authorized_date: null,
      category: [Array],
      category_id: '19046000',
      date: '2019-11-26',
      iso_currency_code: 'USD',
      location: [Object],
      name: 'Madison Bicycle Shop',
      payment_channel: 'in store',
      payment_meta: [Object],
      pending: false,
      pending_transaction_id: null,
      transaction_id: 'zVvmJL5qZjHo57RKQrjqcQz978ZrRBuoLmWmj',
      transaction_type: 'place',
      unofficial_currency_code: null
    }
  ],
  status_code: 200
}